version: '3.9'
services:
  app_security:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
        - 8020:8020
    volumes:
        - .:/app
    networks:
        - fastapi

  db:
    image: postgres:12.0-alpine
    container_name: postgres-db
    ports:
        - 5432:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    networks:
        - fastapi

networks:
  fastapi:
    name: fastapi
    driver: bridge

volumes:
  postgres_data: